annotation:
  auto_save_interval: 60
  backup_count: 5
  export_formats:
  - json
  - csv
  grid_cols: 10
  grid_rows: 12
  growth_levels:
  - negative
  - weak
  - positive
  microbe_types:
  - bacteria
  - fungi
  template_dir: templates
config_file_path: config/app.yaml
data_dir: data
database:
  database: annotation_tool
  host: localhost
  max_overflow: 20
  password: ''
  pool_size: 10
  port: 5432
  username: ''
debug: false
image:
  cache_size: 100
  default_zoom_level: 1.0
  grid_color: '#FF0000'
  grid_width: 2
  max_image_size: 52428800
  max_zoom_level: 5.0
  min_zoom_level: 0.1
  supported_formats:
  - .jpg
  - .jpeg
  - .png
  - .bmp
  - .tiff
log_dir: logs
logging:
  backup_count: 5
  console_output: true
  file_path: logs/app.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10485760
temp_dir: temp
ui:
  auto_hide_panels: false
  font_family: Arial
  font_size: 12
  shortcut_enabled: true
  show_coordinates: true
  show_grid: true
  theme: default
  window_height: 800
  window_width: 1200
